version: '3.7'
services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - 3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db
